# Generated by Django 2.0.4 on 2018-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_private',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
