# Generated by Django 2.0.4 on 2018-05-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180504_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomsdescription',
            options={'verbose_name': 'Rooms description', 'verbose_name_plural': 'Rooms description'},
        ),
    ]
