# Generated by Django 2.0.4 on 2018-05-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=255, verbose_name='Pregunta'),
        ),
    ]
