# Generated by Django 2.0.4 on 2018-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='active',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='subtitle',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='subtitle_es',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title_es',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
