# Generated by Django 2.0.4 on 2018-05-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_images', '0002_auto_20180513_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='title_es',
            field=models.CharField(max_length=30),
        ),
    ]
