# Generated by Django 2.0.4 on 2018-04-16 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('TC', 'Tourist Class'), ('TS', 'Tourist Superior Class'), ('FC', 'First Class')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Cruise Ship',
                'verbose_name_plural': 'Cruise Ships',
            },
        ),
        migrations.CreateModel(
            name='CruiseShipItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('included', models.TextField()),
                ('not_included', models.TextField()),
                ('cruise_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.CruiseShip')),
            ],
            options={
                'verbose_name': 'Cruise Ship Itinerary',
                'verbose_name_plural': 'Cruise Ships Itineraries',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('regular_price', models.FloatField()),
                ('last_minute_price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('cruise_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.CruiseShip')),
            ],
            options={
                'verbose_name': 'Galapagos Deal',
                'verbose_name_plural': 'Galapagos Deals',
            },
        ),
    ]
