# Generated by Django 2.0.4 on 2018-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
