# Generated by Django 2.0.4 on 2018-05-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitiesdescription',
            options={'verbose_name': 'Activities description', 'verbose_name_plural': 'Activities description'},
        ),
    ]
