# Generated by Django 2.0.4 on 2018-10-03 22:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180517_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('text', ckeditor.fields.RichTextField()),
                ('title_es', models.CharField(max_length=25, verbose_name='Titulo')),
                ('text_es', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
