"""
Django settings for hostel project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#e*wq9dx%%o-@d+(hp*ve5*x13^zsfa9@kr%#8lji%$7+0q@tu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'nucapacha.fetux.net', 'nucapacha.com', 'www.nucapacha.com', 'vps-1519120-x.dattaweb.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'hostel.about_us.apps.AboutUsConfig',
    'hostel.activities.apps.ActivitiesConfig',
    'hostel.carousel_images.apps.CarouselImagesConfig',
    'hostel.facilities.apps.FacilitiesConfig',
    'hostel.gallery_images.apps.GalleryImagesConfig',
    'hostel.location.apps.LocationConfig',
    'hostel.rooms.apps.RoomsConfig',
    'hostel.special_offers.apps.SpecialOffersConfig',
    'hostel.terms.apps.TermsConfig',
    'hostel.faqs.apps.FaqsConfig',

    'ckeditor',
    'admin_reorder',
    'bulk_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'hostel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/user/nucapacha.com/hostel/templates', 'hostel/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hostel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = '/home/fetu/nucapacha.com/hostel/about_us/static'
STATIC_URL = '/static/'

MEDIA_ROOT = '/home/fetu/nucapacha.com/uploads'
MEDIA_URL = '/uploads/'

EMAIL_HOST = 'localhost'
EMAIL_PORT = 25


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Basic',
    },
}

ADMIN_REORDER = (
    {'app': 'about_us', 'label': 'Sitio - Gestion de contenido', 'models': (
        {'model': 'about_us.AboutUs', 'label': 'Accerca nuestro'},
        {'model': 'rooms.RoomsDescription', 'label': 'Habitaciones'},
        {'model': 'facilities.Facility', 'label': 'Servicios'},
        {'model': 'activities.ActivitiesDescription', 'label': 'Actividades'},
        {'model': 'location.Location', 'label': 'Ubicacion'},
        {'model': 'terms.Terms', 'label': 'Terminos y Condiciones'},
        {'model': 'faqs.Faq', 'label': 'FAQs'},
    )},
    {'app': 'gallery_images', 'label': 'Galerias - Gestion de imagenes', 'models': (
        {'model': 'gallery_images.GalleryImage', 'label': 'Galeria de Imagenes'},
        {'model': 'carousel_images.CarouselImage', 'label': 'Carousel de Imagenes - FrontPage'},
    )},
    {'app': 'activities', 'label': 'Actividades y Eventos', 'models': (
        {'model': 'activities.Activity', 'label': 'Actividades'},
        {'model': 'activities.Event', 'label': 'Eventos'},

    )},
    {'app': 'rooms', 'label': 'Tarifas y Ofertas', 'models': (
        {'model': 'rooms.Room', 'label': 'Tarifas Habitaciones'},
        {'model': 'special_offers.SpecialOffer', 'label': 'Oferta especial'},
    )},
    {'app': 'auth', 'models': (
        {'model': 'auth.User', 'label': 'Staff'},
    )}
)
