# Generated by Django 2.0.4 on 2018-05-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facilities description', 'verbose_name_plural': 'Facilities description'},
        ),
    ]
