# Generated by Django 2.0.4 on 2018-05-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us description', 'verbose_name_plural': 'About Us description'},
        ),
    ]
