# Generated by Django 2.0.4 on 2018-04-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'El Hostel', 'verbose_name_plural': 'El Hostel'},
        ),
    ]
