# Generated by Django 2.0.4 on 2018-05-01 07:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('text', ckeditor.fields.RichTextField(max_length=70)),
                ('code', models.CharField(max_length=6)),
                ('title_es', models.CharField(max_length=25, verbose_name='Titulo')),
                ('text_es', ckeditor.fields.RichTextField(max_length=70, verbose_name='Texto')),
                ('code_es', models.CharField(max_length=6, verbose_name='Codigo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ofertas Especiales',
                'verbose_name': 'Oferta Especial',
            },
        ),
    ]
