# Generated by Django 2.0.4 on 2018-05-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'verbose_name': 'Special Offer', 'verbose_name_plural': 'Special Offers'},
        ),
    ]
