# Generated by Django 2.0.4 on 2018-07-28 12:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offers', '0002_auto_20180504_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='text_es',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title_es',
            field=models.CharField(max_length=35, verbose_name='Titulo'),
        ),
    ]
