# Generated by Django 2.0.4 on 2018-05-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='text_es',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='title_es',
            field=models.CharField(max_length=120, verbose_name='Titulo'),
        ),
    ]
